"""`doctor` against damaged data — the command whose whole job is saying so.

Three defects, found by breaking each data file three ways (corrupt, empty,
missing) and running the one command that exists to report exactly that:

1. It CRASHED with a JSONDecodeError on a corrupt `config.json`. The diagnostic
   tool failed to diagnose.
2. It reported **"all checks pass"** with a corrupt knowledge graph, a corrupt
   policy book, and a corrupt skill registry, because the checks called
   `os.path.exists` and never parsed anything. That is the same
   existence-is-not-a-measurement mistake found in the installer's interpreter
   probe, the sandbox's unused path guard, and the worktree repo check.
3. It exited **0** while printing "1 check(s) failed", so a script could not act
   on the failure it had just been handed.

Fixing (3) naively would have broken CI: a runner has no agent CLIs installed,
which is a legitimate state and not a defect. Checks therefore carry a severity,
and only blocking ones set the exit code.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from dobby.core.platform import child_env

#: Files whose damage must be reported as BLOCKING.
DATA_FILES = [
    "ontology.json",
    "config.json",
    os.path.join("knowledge", "kg.json"),
    os.path.join("policies", "policies.json"),
    os.path.join("registry", "skills.json"),
    os.path.join("registry", "capabilities.json"),
]

DAMAGE = {"corrupt": "{ this is not json", "empty": "", "missing": None}


#: What `doctor` actually reads. `mcp/` and `tests/` were copied too and no
#: check has ever looked at either, which cost real time: this fixture is built
#: 48 times across the two matrix tests, so every file in the copy is paid for
#: 48 times. Measured after the runtime package landed — 16 more files in
#: `dobby/` and `tests/` — the module went from 227s to 302s and crossed the
#: 300s ceiling that `.dobby/criteria/selfcheck_criteria.json` puts on the whole
#: suite. Copying only what the command reads is the fix; copying less than that
#: would be a fixture that passes for the wrong reason, so `dobby/` stays whole.
_NEEDED_BY_DOCTOR = ("dobby", "evals")

#: Ignored inside the copy. Compiled bytecode is regenerated by the child
#: process anyway, and `.dobby/state/` is machine-local run output that grows
#: without bound — a fixture that copies it gets slower every time somebody runs
#: the harness in this checkout.
_SKIP = shutil.ignore_patterns("__pycache__", "*.pyc")


def make_repo(*, drop_bootstrap: bool = False) -> str:
    """A minimal runnable copy of the kit — minimal meaning what `doctor` reads."""
    d = tempfile.mkdtemp(prefix="dobby-doctor-")
    for sub in _NEEDED_BY_DOCTOR:
        shutil.copytree(os.path.join(REPO, sub), os.path.join(d, sub),
                        ignore=_SKIP)
    shutil.copytree(os.path.join(REPO, ".dobby"), os.path.join(d, ".dobby"),
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc",
                                                  "state"))
    if drop_bootstrap:
        boot = os.path.join(d, ".dobby", "knowledge", "kg.bootstrap.json")
        if os.path.exists(boot):
            os.remove(boot)
    return d


def run_doctor(repo: str):
    proc = subprocess.run(
        [sys.executable, "-m", "dobby.cli", "doctor"], cwd=repo,
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        env=child_env(), timeout=180)
    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError:
        payload = None
    return proc.returncode, payload, proc.stderr


class TestHealthyRepo(unittest.TestCase):
    def test_passes_and_exits_zero(self):
        """Assert the CONTRACT, not a verdict string that varies by machine.

        This test originally required the exact text "all checks pass", which
        encoded the authoring machine's incidental state: a `kg.bootstrap.json`
        left behind by dogfooding (gitignored, so absent from any checkout) and
        four installed agent CLIs. On a fresh clone the honest verdict is
        "usable, with 1 advisory gap(s): bootstrapped", and the assertion failed
        — in CI, on every OS, on every commit, while passing locally.

        The contract is that undamaged data produces no BLOCKING failure and a
        zero exit. Advisory gaps are expected on a machine that has not been
        bootstrapped and has no providers installed, which describes every CI
        runner.
        """
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        rc, payload, err = run_doctor(d)
        self.assertIsNotNone(payload, f"doctor emitted no JSON: {err[-300:]}")
        self.assertEqual(payload["blocking_failures"], [],
                         f"undamaged data reported a blocking failure: "
                         f"{payload['verdict']}")
        self.assertEqual(rc, 0, payload["verdict"])

    def test_verdict_wording_matches_the_state_it_found(self):
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        _, payload, _ = run_doctor(d)
        if payload["advisory_gaps"]:
            self.assertIn("advisory", payload["verdict"])
        else:
            self.assertEqual(payload["verdict"], "all checks pass")


class TestDamageIsReportedNotCrashed(unittest.TestCase):
    """Every damage shape, every required file. 18 scenarios."""

    def test_no_scenario_crashes(self):
        crashes = []
        for rel in DATA_FILES:
            for kind, content in DAMAGE.items():
                d = make_repo()
                try:
                    path = os.path.join(d, ".dobby", rel)
                    if content is None:
                        os.remove(path)
                    else:
                        with open(path, "w", encoding="utf-8") as f:
                            f.write(content)
                    _, payload, err = run_doctor(d)
                    if payload is None or "Traceback" in err:
                        crashes.append(f"{rel}/{kind}: {err.strip()[-160:]}")
                finally:
                    shutil.rmtree(d, ignore_errors=True)
        self.assertEqual(crashes, [], "\n".join(crashes))

    def test_every_damage_is_detected_and_named(self):
        misses = []
        for rel in DATA_FILES:
            for kind, content in DAMAGE.items():
                d = make_repo()
                try:
                    path = os.path.join(d, ".dobby", rel)
                    if content is None:
                        os.remove(path)
                    else:
                        with open(path, "w", encoding="utf-8") as f:
                            f.write(content)
                    rc, payload, _ = run_doctor(d)
                    if payload is None:
                        misses.append(f"{rel}/{kind}: no output")
                        continue
                    named = any(rel in c for c in payload["blocking_failures"])
                    if rc == 0 or not named:
                        misses.append(
                            f"{rel}/{kind}: rc={rc} "
                            f"blocking={payload['blocking_failures']}")
                finally:
                    shutil.rmtree(d, ignore_errors=True)
        self.assertEqual(misses, [], "\n".join(misses))

    def test_corrupt_config_does_not_crash_the_diagnostic(self):
        """The original failure: JSONDecodeError from `doctor` itself."""
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        with open(os.path.join(d, ".dobby", "config.json"), "w",
                  encoding="utf-8") as f:
            f.write("{ nope")
        rc, payload, err = run_doctor(d)
        self.assertIsNotNone(payload, f"doctor crashed: {err[-300:]}")
        self.assertNotIn("Traceback", err)
        self.assertIn("config_readable", payload["blocking_failures"])

    def test_parse_failure_is_reported_not_just_existence(self):
        """`os.path.exists` said yes while the file was unreadable JSON."""
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        with open(os.path.join(d, ".dobby", "knowledge", "kg.json"), "w",
                  encoding="utf-8") as f:
            f.write("{ broken")
        rc, payload, _ = run_doctor(d)
        self.assertEqual(rc, 1)
        row = next(c for c in payload["checks"] if "kg.json" in c["check"])
        self.assertFalse(row["ok"])
        self.assertIn("NOT valid JSON", row["detail"])

    def test_empty_object_is_not_healthy_data(self):
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        with open(os.path.join(d, ".dobby", "policies", "policies.json"), "w",
                  encoding="utf-8") as f:
            f.write("{}")
        rc, payload, _ = run_doctor(d)
        self.assertEqual(rc, 1)


class TestSeverity(unittest.TestCase):
    """Fixing the exit code naively would have made every CI run red."""

    def test_missing_providers_is_advisory_not_blocking(self):
        """A CI runner has no agent CLIs by design. That is thin, not broken."""
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        rc, payload, _ = run_doctor(d)
        for name in ("providers", "multi_agent"):
            row = next(c for c in payload["checks"] if c["check"] == name)
            self.assertFalse(row["blocking"],
                             f"{name} must not set the exit code")

    def test_unbootstrapped_is_advisory(self):
        d = make_repo(drop_bootstrap=True)
        self.addCleanup(shutil.rmtree, d, True)
        rc, payload, _ = run_doctor(d)
        self.assertEqual(rc, 0, payload["verdict"])
        self.assertIn("bootstrapped", payload["advisory_gaps"])
        self.assertEqual(payload["blocking_failures"], [])
        self.assertIn("usable", payload["verdict"])

    def test_corrupt_data_is_blocking(self):
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        with open(os.path.join(d, ".dobby", "ontology.json"), "w",
                  encoding="utf-8") as f:
            f.write("{ broken")
        rc, payload, _ = run_doctor(d)
        self.assertEqual(rc, 1)
        self.assertIn("BLOCKING", payload["verdict"])

    def test_every_check_declares_its_severity(self):
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        _, payload, _ = run_doctor(d)
        for row in payload["checks"]:
            self.assertIn("blocking", row, f"{row['check']} has no severity")

    def test_advisory_gaps_are_still_reported(self):
        """Not setting the exit code must not mean going unmentioned."""
        d = make_repo(drop_bootstrap=True)
        self.addCleanup(shutil.rmtree, d, True)
        _, payload, _ = run_doctor(d)
        self.assertTrue(payload["advisory_gaps"])
        self.assertIn("advisory", payload["verdict"])


#: Every subcommand that does not need a provider or a network call.
ALL_COMMANDS = [
    ["doctor"], ["route", "x"], ["context", "x"], ["fleet"],
    ["memory", "stats"], ["memory", "integrity"], ["specialize"],
    ["research", "plan", "x"], ["design"], ["review", "--reviewers", "2"],
    ["tokens", "policy"], ["pipeline", "--budget", "4"], ["sandbox", "sweep"],
    ["spend"], ["spend", "--line"], ["handoff-latest"], ["friction-report"],
    ["panel", "x", "--size", "2", "--dry-run"], ["prompt", "이거 고쳐줘"],
    ["style", "--text", "hello world"],
]


def run_cli(repo: str, argv: list):
    proc = subprocess.run(
        [sys.executable, "-m", "dobby.cli", *argv], cwd=repo,
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        env=child_env(), timeout=180)
    return proc.returncode, proc.stdout, proc.stderr


class TestNoCommandEverShowsATraceback(unittest.TestCase):
    """Damaged data must stop a command — legibly, not with a Python stack.

    A command that cannot load its data SHOULD fail: running against defaults
    nobody chose is worse than stopping. But it stopped with a raw
    `json.decoder.JSONDecodeError`, which tells the user which line of CPython's
    parser was unhappy and not which of their files to fix. Four commands failed
    that way on a corrupt config.
    """

    def test_healthy_repo_runs_every_command(self):
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        shutil.copy(os.path.join(REPO, "DESIGN.md"), d)
        failures = []
        for argv in ALL_COMMANDS:
            rc, _, err = run_cli(d, argv)
            if "Traceback" in err:
                failures.append(f"{' '.join(argv)}: {err.strip()[-120:]}")
        self.assertEqual(failures, [], "\n".join(failures))

    def test_damaged_data_never_produces_a_traceback(self):
        crashed = []
        for damaged in ("ontology.json", "config.json",
                        os.path.join("knowledge", "kg.json"),
                        os.path.join("registry", "skills.json")):
            d = make_repo()
            try:
                shutil.copy(os.path.join(REPO, "DESIGN.md"), d)
                with open(os.path.join(d, ".dobby", damaged), "w",
                          encoding="utf-8") as f:
                    f.write("{ broken")
                for argv in ALL_COMMANDS:
                    _, _, err = run_cli(d, argv)
                    if "Traceback" in err:
                        crashed.append(f"{damaged} + {' '.join(argv)}")
            finally:
                shutil.rmtree(d, ignore_errors=True)
        self.assertEqual(crashed, [], f"commands that crashed: {crashed}")

    def test_the_refusal_names_the_file_and_points_at_doctor(self):
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        with open(os.path.join(d, ".dobby", "config.json"), "w",
                  encoding="utf-8") as f:
            f.write("{ broken")
        rc, _, err = run_cli(d, ["route", "x"])
        self.assertEqual(rc, 2)
        self.assertTrue(err.startswith("dobby:"), err[:120])
        self.assertIn("config.json", err)
        self.assertIn("dobby doctor", err)

    def test_a_missing_file_is_named_too(self):
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        os.remove(os.path.join(d, ".dobby", "ontology.json"))
        rc, _, err = run_cli(d, ["context", "x"])
        self.assertEqual(rc, 2)
        self.assertIn("missing", err)
        self.assertIn("ontology.json", err)

    def test_commands_that_do_not_need_the_damaged_file_still_work(self):
        """A corrupt knowledge graph must not stop `dobby style`."""
        d = make_repo()
        self.addCleanup(shutil.rmtree, d, True)
        with open(os.path.join(d, ".dobby", "knowledge", "kg.json"), "w",
                  encoding="utf-8") as f:
            f.write("{ broken")
        rc, _, err = run_cli(d, ["style", "--text", "hello world"])
        self.assertEqual(rc, 0, err[-200:])


if __name__ == "__main__":
    unittest.main()
